sap.ui.define([], function () {
	return Object.freeze({
		STATUS_PENDING: "PENDING",
		APPROV_L2: "APPROV_L2",
		EMPLOYEE: "EMPLOYEE",
		MANAGER: "MANAGER",
		SUPERVISOR: "SUPERVISOR",
		MD_LEVEL: "MD_LEVEL",
		HR_ADMIN: "HR_ADMIN",
		REQUESTOR: "REQUESTOR",
		SENT: "SENT",
		REJECTED: "REJECTED",
		CANCELED: "CANCELED",
		PENDWITHDR: "PENDWITHDR",
		REJWITHDR: "REJWITHDR",
		PRE_APPROV: "PRE_APPROV",
		SHIFT_TYPE_OFF: "OFF",
		SHIFT_TYPE_WORK: "WORK",
		APPROVED: "APPROVED"
	});
});